apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wedding
  name: wedding-service-deployment
  labels:
    app: wedding-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wedding-service
  template:
    metadata:
      labels:
        app: wedding-service
    spec:
      containers:
        - name: wedding-service
          image: ghcr.io/lucascarioca/wedding-registration-service:latest
          ports:
            - containerPort: 80
              name: wl-http
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: wedding-registration-service
                  key: API_KEY
            - name: CONN_STR
              valueFrom:
                secretKeyRef:
                  name: wedding-registration-service
                  key: CONN_STR
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: wedding-registration-service
                  key: TABLE_NAME
            - name: PARTITION
              valueFrom:
                secretKeyRef:
                  name: wedding-registration-service
                  key: PARTITION
---
apiVersion: v1
kind: Service
metadata:
  namespace: wedding
  name: wedding-service-service
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 80
      nodePort: 30103
      targetPort: ws-http
  selector:
    app: wedding-service
